# Generated by Django 2.2 on 2019-05-11 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20, verbose_name='Verification Content')),
                ('lic_feature_base_a', models.BooleanField(verbose_name='License Feature Base_A')),
                ('lic_feature_base_b', models.BooleanField(verbose_name='License Feature Base_B')),
                ('lic_feature_base_c', models.BooleanField(verbose_name='License Feature Base_C')),
                ('lic_feature_opt_1', models.BooleanField(verbose_name='License Feature Option_1')),
                ('lic_feature_opt_2', models.BooleanField(verbose_name='License Feature Option_2')),
                ('lic_feature_opt_3', models.BooleanField(verbose_name='License Feature Option_3')),
                ('time_create', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Time(Create)')),
                ('time_update', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Time(Update)')),
                ('user_create', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ContentUserCreate', to=settings.AUTH_USER_MODEL, verbose_name='User(Create)')),
                ('user_update', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ContentUserUpdate', to=settings.AUTH_USER_MODEL, verbose_name='User(Update)')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_node', models.CharField(max_length=20, verbose_name='Technology Node')),
                ('lic_feature_16nm', models.BooleanField(verbose_name='16nm')),
                ('lic_feature_7nm', models.BooleanField(verbose_name='7nm')),
                ('time_create', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Time(Create)')),
                ('time_update', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Time(Update)')),
                ('user_create', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TechUserCreate', to=settings.AUTH_USER_MODEL, verbose_name='User(Create)')),
                ('user_update', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TechUserUpdate', to=settings.AUTH_USER_MODEL, verbose_name='User(Update)')),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=20, verbose_name='Product Name(Design Phase)')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('frequency', models.IntegerField(verbose_name='Frequency of Use [%]')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('time_create', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Time(Create)')),
                ('time_update', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Time(Update)')),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='VerificationContent', to='demand_manager.VerificationContent', verbose_name='Verification Content')),
                ('tech_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='techNode', to='demand_manager.Technology', verbose_name='Technology Node')),
                ('user_create', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DemandUserCreate', to=settings.AUTH_USER_MODEL, verbose_name='User(Create)')),
                ('user_update', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DemandUserUpdate', to=settings.AUTH_USER_MODEL, verbose_name='User(Update)')),
            ],
        ),
    ]
