# Generated by Django 2.2 on 2019-05-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lic_type', models.CharField(choices=[('Base', 'Base License'), ('Peak', 'Peak License')], max_length=20, verbose_name='License Type')),
                ('lic_feature', models.CharField(max_length=20, verbose_name='License Feature')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('num_lic_feature', models.IntegerField(verbose_name='Number of Released License Feature')),
            ],
        ),
    ]
