# Generated by Django 2.2 on 2019-05-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand',
            old_name='start_date',
            new_name='startdate',
        ),
    ]
