# Generated by Django 2.2 on 2019-05-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand_manager', '0002_auto_20190506_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand',
            old_name='startdate',
            new_name='start_date',
        ),
    ]
