# Generated by Django 2.2 on 2019-06-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand_manager', '0002_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='frequency',
            field=models.IntegerField(help_text='<ul><li>Required</li></ul>', verbose_name='Frequency of Use [%]'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='product',
            field=models.CharField(help_text='<ul><li>Required</li></ul>', max_length=20, verbose_name='Product Name(Design Phase)'),
        ),
        migrations.AlterField(
            model_name='verificationcontent',
            name='lic_feature_base_a',
            field=models.IntegerField(default=0, verbose_name='License Feature Base_A'),
        ),
        migrations.AlterField(
            model_name='verificationcontent',
            name='lic_feature_base_b',
            field=models.IntegerField(default=0, verbose_name='License Feature Base_B'),
        ),
        migrations.AlterField(
            model_name='verificationcontent',
            name='lic_feature_base_c',
            field=models.IntegerField(default=0, verbose_name='License Feature Base_C'),
        ),
        migrations.AlterField(
            model_name='verificationcontent',
            name='lic_feature_opt_1',
            field=models.IntegerField(default=0, verbose_name='License Feature Option_1'),
        ),
        migrations.AlterField(
            model_name='verificationcontent',
            name='lic_feature_opt_2',
            field=models.IntegerField(default=0, verbose_name='License Feature Option_2'),
        ),
        migrations.AlterField(
            model_name='verificationcontent',
            name='lic_feature_opt_3',
            field=models.IntegerField(default=0, verbose_name='License Feature Option_3'),
        ),
    ]
