# Generated by Django 2.2 on 2019-06-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand_manager', '0003_auto_20190604_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcontent',
            name='lic_feature_base_b',
            field=models.BooleanField(verbose_name='License Feature Base_B'),
        ),
        migrations.AlterField(
            model_name='verificationcontent',
            name='lic_feature_base_c',
            field=models.BooleanField(verbose_name='License Feature Base_C'),
        ),
        migrations.AlterField(
            model_name='verificationcontent',
            name='lic_feature_opt_1',
            field=models.BooleanField(verbose_name='License Feature Option_1'),
        ),
        migrations.AlterField(
            model_name='verificationcontent',
            name='lic_feature_opt_2',
            field=models.BooleanField(verbose_name='License Feature Option_2'),
        ),
        migrations.AlterField(
            model_name='verificationcontent',
            name='lic_feature_opt_3',
            field=models.BooleanField(verbose_name='License Feature Option_3'),
        ),
    ]
